key: value

import dagshub
dagshub.init(repo_owner='vasim-rgb',
             repo_name='mlops-movie-recommender-end-to-end',
             mlflow=True)

import mlflow
with mlflow.start_run():
  mlflow.log_param('parameter name', 'value')
  mlflow.log_metric('metric name', 1)