artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Arshiagosh/TMDB-5000-Movie-Dataset-Analysis-and-Modeling/raw/7b87c2fbd9809dbcdc04718c98ca513beec8224f/datasets.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir_movies: artifacts/data_ingestion/tmdb_5000_movies.csv
  unzip_data_dir_cred: artifacts/data_ingestion/tmdb_5000_credits.csv
  joined_data_path: artifacts/data_validation/joined_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_validation/joined_data.csv
  transformed_data_path: artifacts/data_transformation/transformed_data.csv

model_trainer:
  root_dir: artifacts/model_trainer
  transformed_data_path: artifacts/data_transformation/transformed_data.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  #test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
  data_path: artifacts/data_validation/joined_data.csv
  